CREATE TABLE IF NOT EXISTS extras (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nev VARCHAR(200) NOT NULL,
  ar INT NOT NULL,
  kategoriaId INT NOT NULL,
  tipus ENUM('pizza', 'hamburger') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (kategoriaId) REFERENCES kategoria(id) ON DELETE CASCADE
);

INSERT INTO extras (nev, ar, kategoriaId, tipus) VALUES
('Pizza szósz', 300, 1, 'pizza'),
('Tejfölös alap', 300, 1, 'pizza'),
('BBQ alap', 400, 1, 'pizza'),
('Erős pizza szósz', 400, 1, 'pizza'),
('Jalapeno', 300, 1, 'pizza'),
('Bab', 300, 1, 'pizza'),
('Kukorica', 300, 1, 'pizza'),
('Gomba', 250, 1, 'pizza'),
('Hagyma', 250, 1, 'pizza'),
('Sajt', 500, 1, 'pizza'),
('Füstölt sajt', 600, 1, 'pizza'),
('Gorgonzola', 700, 1, 'pizza'),
('Csirkehús', 700, 1, 'pizza'),
('Ananász', 400, 1, 'pizza'),
('Tojás', 200, 1, 'pizza'),
('Paradicsom', 300, 1, 'pizza'),
('Sonka', 700, 1, 'pizza'),
('Szalámi', 700, 1, 'pizza'),
('Bacon', 700, 1, 'pizza'),
('Tarja', 700, 1, 'pizza'),
('Olivabogyó', 300, 1, 'pizza'),
('Tonhal', 800, 1, 'pizza'),
('Citrom', 350, 1, 'pizza'),
('Parmezán', 600, 1, 'pizza'),
('Hamburger doboz', 200, 2, 'hamburger'),
('Grill camembert', 690, 2, 'hamburger'),
('Sertés hamburger hús', 600, 2, 'hamburger'),
('Marha gyros hús', 900, 2, 'hamburger'),
('Rántott sajt', 400, 2, 'hamburger'),
('Bacon', 250, 2, 'hamburger'),
('Sajt', 200, 2, 'hamburger'),
('Marhajó csípős', 300, 2, 'hamburger'),
('Jalapeno paprika', 250, 2, 'hamburger'),
('Vörös cheddar sajt', 200, 2, 'hamburger'),
('Áfonyalekvár 300', 50, 2, 'hamburger'),
('BBQ szósz 300', 50, 2, 'hamburger'),
('Tartármártás 300', 50, 2, 'hamburger'),
('Ketchup 300', 50, 2, 'hamburger'),
('Majonéz 300', 50, 2, 'hamburger'),
('Monster szósz 300', 50, 2, 'hamburger'),
('Marhajó csípős 300', 50, 2, 'hamburger'),
('Málna öntött 100', 50, 2, 'hamburger'),
('Csoki öntött 100', 50, 2, 'hamburger'),
('Pizza szósz 400', 50, 2, 'hamburger'),
('Tejföl 350', 50, 2, 'hamburger'),
('Egy kávé neki aki a rendelésed készíti', 300, 2, 'hamburger'),
('Egy csoki neki amiért hamar kiér hozzád', 300, 2, 'hamburger'),
('Menü hasáb + dobozos üdítő 1400', 150, 2, 'hamburger'),
('Steak burgonya + dobozos üdítő 1400', 150, 2, 'hamburger'),
('Édes burgonya + üdítő 1600', 150, 2, 'hamburger');

CREATE TABLE IF NOT EXISTS kosar (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  termekId INT NOT NULL,
  termekNev VARCHAR(200) NOT NULL,
  alapAr INT NOT NULL,
  mennyiseg INT NOT NULL DEFAULT 1,
  vegosszeg INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (termekId) REFERENCES termek(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS kosar_extras (
  id INT AUTO_INCREMENT PRIMARY KEY,
  kosarId INT NOT NULL,
  extraId INT NOT NULL,
  extraNev VARCHAR(200) NOT NULL,
  extraAr INT NOT NULL,
  mennyiseg INT NOT NULL DEFAULT 1,
  FOREIGN KEY (kosarId) REFERENCES kosar(id) ON DELETE CASCADE,
  FOREIGN KEY (extraId) REFERENCES extras(id) ON DELETE CASCADE
);

